repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["--target-version=py27", "--target-version=py37"]

  #- repo: https://github.com/pre-commit/pre-commit-hooks
    #rev: v2.0.0
    #hooks:
      #- id: flake8

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config
        args: [
          --application-directories=src/requirementslib,
          --settings-path=./,
        ]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort

